### ISSUE TITLE
can't use gpu when output.shape[1]*nnz(a)>2e31

### ISSUE THREAD

**Issue by passermyh** [ZJU-DAILY/DualMatch#2]
![image](https://github.com/ZJU-DAILY/DualMatch/assets/71198047/a1b3be90-66d4-43bb-a44a-87e46a650585)

**Comment by xz-liu** [comment]
This is probably due to TensorFlow's sparse computation limitations. We may refactor the code in the future to avoid this issue. Until then, please use the CPU for this part. I am sorry for the inconvenience.
